name: Python CI Pipeline

# Trigger: This makes the pipeline run every time you push code
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Download your code onto the GitHub server
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Python 3.11
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. Install the tools from your recipe file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Run your automated tests
    - name: Run Tests with Pytest
      run: |
        python -m pytest
